volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
#  production_traefik: {}
  production_django_media: {}

  production_redis_data: {}



services:
  django: &django
    container_name: ecommerce
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: your_project_name_production_django
    volumes:
      - production_django_media:/apps/apps/media
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

    ports:
      - '8009:8009'

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: your_project_name_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: docker.io/redis:6

    volumes:
      - production_redis_data:/data


#  nginx:
#    build:
#      context: .
#      dockerfile: ./compose/production/nginx/Dockerfile
#    image: tourism_management_production_nginx
#    depends_on:
#      - django
#    volumes:
#      - production_django_media:/usr/share/nginx/media:ro
