services:
  docs:
    image: tourism_management_local_docs
    container_name: tourism_management_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/apps/config:z
      - ./apps:/apps/apps:z
    ports:
      - '9000:9000'
    command: /start-docs
