volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_django_media: {}
  production_redis_data: {}


services:
  django:
    build:
      context: .
      dockerfile: compose/production/django/Dockerfile

    image: your_production
    container_name: your_production
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    command: /start
    ports:
      - "127.0.0.1:8080:8080"

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: my_awesome_project_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/18/docker
      - production_postgres_data_backups:/backups
    env_file:
      - .env

  redis:
    image: docker.io/redis:7.2

    volumes:
      - production_redis_data:/data
