volumes:
  postgres_data: {}
  production_postgres_data_backups: {}
  production_django_media: {}


services:
  django:
    build:
      context: .
      dockerfile: compose/production/django/Dockerfile

    image: your_production
    container_name: your_production
    volumes:
      - production_django_media:/app/apps/media
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres

    ports:
      - "127.0.0.1:8081:5000"

    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: your_production_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: docker.io/redis:6

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: your_production_nginx
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
