volumes:
  your_local_postgres: {}
  your_local_postgres_backups: {}


services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: your_local
    container_name: your_local
    depends_on:
      - postgres
    volumes:
      - .:/app:z

    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres

    ports:
      - '8080:8080'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: your_local_postgres
    container_name: your_local_postgres
    volumes:
      - your_local_postgres:/var/lib/postgresql/data
      - your_local_postgres_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

#    ports:
#      - '5433:5432'
